Gcr devel
ginkgo-project/ginkgo pull request #1022
Opened 2022-04-14 07:33 UTC by kho19

2022-04-14 07:36 UTC, upsj commented
label!

2022-04-14 07:36 UTC, upsj commented
check-format!

2022-04-19 13:03 UTC, MarcelKoch commented
Thanks @kho19 for your contribution. Before I get to reviewing, do you mind posting a literature reference for the algorithm you've implemented? It would also be nice to have that reference in the code documentation.

2022-04-19 14:43 UTC, yhmtsai reviewed
Could you add the description for this pull requirement?

2022-04-20 08:52 UTC, kho19 commented
GCR was based on the description in _Iterative methods for sparse linear systems_ by Yousef Saad. I'll include this in the documentation.

2022-06-02 11:09 UTC, MarcelKoch requested changes
The implementation looks good. I've remarked mostly some formatting stuff.

The largest issue I have is that there are no reference tests. This needs to be fixed since you compare the other implementations to the reference one.

Also, I think this needs to be rebased. I'm not sure if the changes in the gmres code are due to this PR or the gmres refactoring one, so I skipped all of them.

2022-06-02 11:09 UTC, MarcelKoch commented on test/solver/gcr_kernels.cpp
> +
```suggestion
```

2022-06-02 11:09 UTC, MarcelKoch commented on test/solver/gcr_kernels.cpp
> +
```suggestion
```

2022-11-03 19:32 UTC, closed without merging