Push mirroring
ginkgo-project/ginkgo pull request #1084
Opened 2022-07-20 09:36 UTC by tcojean

This adds push mirroring for the current branch.

The way it works is simple, add the GitLab remote, the ssh key, push force, and prune as needed.

See: https://gitlab.com/ginkgo-project/ginkgo-public-ci/-/pipelines/592229289

Questions: 
* is there any implication of this our current workflow, do labels work as intended, etc?
* should we try pushing all branches simultaneously instead of only the current branch?

2022-07-20 09:55 UTC, upsj commented
Since I've pushed to Gitlab manually before, I'd say this should work w.r.t. labels and statuses.
Not 100% happy with it from the security perspective - looks like we're pulling `mirror.sh` from the current branch. If we used pull_request_target and the sync operation, we'd always rely on the script in `develop`/`master`. That could also be extended to PR comments etc. We'd only lose the ability to automatically sync non-PR branches.

2022-07-20 10:05 UTC, tcojean commented
In terms of security, I agree we should pull from develop in the future like it is done for the other scripts, but that would require first merging this PR before adapting it.

Originally, I also wanted to do this through the PR setup, but I think we should still provide CI for non-PR branches as well so I did it this way.

2022-07-20 10:07 UTC, upsj commented
We can do something like I did with https://github.com/upsj/ginkgo-bot-playground to make sure things work before merging.

2022-07-20 10:13 UTC, yhmtsai commented
depends on who's the trigger and use develop or pull request one?
using wget to get the develop should always work?

2022-07-20 16:25 UTC, tcojean commented
Here is a new version of the script which works like the rest, but is still on `push` rather than on PR. It works even for develop (I reset `ginkgo-public-ci` to the correct commit afterward:

https://github.com/tcojean/ginkgo-bot-playground/runs/7433510967
https://gitlab.com/ginkgo-project/ginkgo-public-ci/-/pipelines/592683601

2022-07-21 12:40 UTC, yhmtsai requested changes
it does not set correctly from the github action output in the playground
```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```

2022-07-21 12:40 UTC, yhmtsai commented on .github/mirror.sh
> +git push --force --prune gitlab $BRANCH_NAME
I need to use `HEAD:$BRANCH_NAME` or `fork/$BRACNH_NAME:$BRANCH_NAME`
otherwise, I get "error: src refspec test does not match any."

2022-07-21 12:40 UTC, yhmtsai commented on .github/mirror.sh
> +git push --force --prune gitlab $BRANCH_NAME
`git checkout -b fork/$BRANCH_NAME` only creates the branch on the current folder, so it does not switch to the branch from fork

2022-07-21 12:51 UTC, yhmtsai commented on .github/mirror.sh
> +git push --force --prune gitlab $BRANCH_NAME
it seems not to delete the unexisting branch?

2022-07-21 13:38 UTC, tcojean commented
It now works also on the playground, it was mostly due to an error in the playground setup rather than in the script (ssh key setup).
See: https://github.com/tcojean/ginkgo-bot-playground/runs/7450389602

I already deleted the branch on the `ginkgo-public-ci` side.

2022-07-22 06:37 UTC, upsj approved these changes
LGTM! Thanks for tackling this!

2022-07-22 06:37 UTC, upsj commented on .github/mirror.sh
> +git config user.name "Ginkgo Bot"
nit: should be unnecessary, since you don't commit anything

2022-07-22 08:15 UTC, yhmtsai approved these changes
LGTM

2022-07-22 08:18 UTC, merged