Accept only unique_ptr for distributed vector constructors
ginkgo-project/ginkgo pull request #1284
Opened 2023-02-17 15:57 UTC by MarcelKoch

Inspired by #1279 I decided to clear up the ownership transfer in the distributed vector constructor. Currently, distributed vectors can be created from existing local vectors by passing them as raw pointers to the constructor. But the constructor will move from the passed in pointer, so this is potentially unsafe. 
One argument in favor of raw pointers was that working with views of local vectors would be simpler (I think?). Since now there is a helper function to create a view of a dense vector, this can now be done as easily with a `unique_ptr` parameter.

To make this work, I had to add `create_const` functions, but I guess that might be useful anyway.

2023-02-20 13:19 UTC, upsj approved these changes
LGTM! We should probably merge this after the pointer_param PR is merged?

2023-02-20 13:24 UTC, MarcelKoch commented
@upsj yes, since this is based on that PR, that makes the most sense.

2023-02-23 14:24 UTC, MarcelKoch commented
format-rebase!

2023-02-23 14:33 UTC, fritzgoebel approved these changes
LGTM

2023-02-23 15:51 UTC, thoasm requested changes
Tests for new functions `create_const` are missing.

2023-02-23 16:59 UTC, thoasm approved these changes
LGTM!

2023-02-24 21:57 UTC, upsj approved these changes

2023-03-08 13:49 UTC, MarcelKoch commented
rebase!

2023-03-13 07:36 UTC, MarcelKoch commented
rebase!

2023-03-14 08:09 UTC, merged