Reusable permutation and transpose
ginkgo-project/ginkgo pull request #1338
Opened 2023-05-16 09:54 UTC by upsj

As a tool for implementing reusable factories, this adds reusable functionality for all Csr permutation and transpose functions.

It also takes a first step towards making `Permutation` the default representation of a reordering.

Closes #1157

2023-06-29 09:09 UTC, MarcelKoch commented
Just a comment, but Csr now has 18 (!) function for permutation. IMO that is too much, at least the `array` ones should be deprecated, since, as far as I understood it, we would move to the `Permutation` interface.

2025-02-14 15:17 UTC, MarcelKoch requested changes
In general LGTM, I would like to discuss the difference between returning both the reuse info with the transposed/permuted matrix and just the reuse info.
If the use case for the reuse info is to be used only once or twice, the current approach makes sense.
If, however, it should be applied in a loop (or similar) then I think returning only the reuse info should lead to more uniform control flow.

2025-02-14 15:17 UTC, MarcelKoch commented on include/ginkgo/core/matrix/csr.hpp
> +    std::unique_ptr<Dense<ValueType>> create_value_view();
maybe keep those as free functions in our core?

2025-02-14 15:17 UTC, MarcelKoch commented on core/matrix/csr.cpp
> +        exec, nnz, reinterpret_cast<FloatIndexType*>(iota_values.get_data()));
TBH I'm a bit skeptical about this. Isn't this UB?

2025-02-14 15:39 UTC, upsj commented on include/ginkgo/core/matrix/csr.hpp
> +    std::pair<std::unique_ptr<Csr>, permuting_reuse_info> transpose_reuse()
doing the operation twice seems like an unnecessary pessimization - maybe alternatively we could somehow make the reuse object a reference parameter, but that makes initialization more complicated, and makes it easier to misuse (what if the existing reuse info has the correct size but incorrect data? We can't really recognize that). It might make sense to give the reuse info a default constructor or at least size-independent constructor though, to allow a pattern like
```
std::unique_ptr<Csr> transposed;
permuting_reuse_info reuse;
...
if(!transposed) {
std::tie(transposed, permuting_reuse_info) = std::move(mtx->transpose_reuse());
}
```

2025-02-14 15:44 UTC, upsj commented on core/matrix/csr.cpp
> +        exec, nnz, reinterpret_cast<FloatIndexType*>(iota_values.get_data()));
Yes, but we are provoking the same kind of nasal demons elsewhere - we don't really care about object provenance for index and value types, because we allocate the data using a pointer allocated via an untyped `::operator new`. The point here is that the compiler can't do anything with this information, because we always pass it through the ABI boundary between the ginkgo and ginkgo_... libraries, only the kernels actually access these values through regular typed pointers instead of a memcpy.

2025-02-18 12:56 UTC, MarcelKoch commented on core/matrix/csr.cpp
> +        exec, nnz, reinterpret_cast<FloatIndexType*>(iota_values.get_data()));
Thanks for the clarification. If the bit patterns match, then I guess we can live with it.

2025-02-18 13:32 UTC, upsj commented on include/ginkgo/core/matrix/csr.hpp
> +    std::pair<std::unique_ptr<Csr>, permuting_reuse_info> transpose_reuse()
I made the type default-constructible now.

2025-02-18 13:32 UTC, upsj commented on include/ginkgo/core/matrix/csr.hpp
> +     *         matrix.
fixed

2025-02-18 13:33 UTC, upsj commented on include/ginkgo/core/matrix/csr.hpp
> +    std::unique_ptr<Dense<ValueType>> create_value_view();
Where would be the right place to put them? I could create a new internal csr header, but maybe that's overkill?

2025-02-18 13:38 UTC, upsj commented on include/ginkgo/core/matrix/csr.hpp
> +    std::pair<std::unique_ptr<Csr>, permuting_reuse_info> transpose_reuse()
Also maybe to be more precise, my goal is for this to be used internally to implement reuse information for complex solvers, usage by applications should be restricted to advanced use cases

2025-02-18 13:59 UTC, MarcelKoch commented on include/ginkgo/core/matrix/csr.hpp
> +    std::unique_ptr<Dense<ValueType>> create_value_view();
I thought they were only used in `csr.cpp`, but now I see that they are also used in tests, so I'm fine with them as it is.

2025-02-18 14:00 UTC, MarcelKoch commented on include/ginkgo/core/matrix/csr.hpp
> +    std::pair<std::unique_ptr<Csr>, permuting_reuse_info> transpose_reuse()
That makes sense. Anyway, fine with me as it is.

2025-02-18 14:03 UTC, MarcelKoch approved these changes

2025-02-18 14:03 UTC, MarcelKoch commented on core/matrix/csr.cpp
> +    : permuting_reuse_info{nullptr}
Isn't this just the default constructor?

2025-02-18 14:04 UTC, upsj commented on core/matrix/csr.cpp
> +    : permuting_reuse_info{nullptr}
this is calling the other permuting_reuse_info constructor, not the value_permutation constructor, if that's what you mean?

2025-02-18 14:05 UTC, MarcelKoch commented on core/matrix/csr.cpp
> +    : permuting_reuse_info{nullptr}
Oh, I see. But doesn't that still have the same effect as the default constructor?

2025-02-18 14:07 UTC, upsj commented on core/matrix/csr.cpp
> +    : permuting_reuse_info{nullptr}
yes, I just wanted to base everything on a single implementation of the constructor, no deep other reason behind it.

2025-02-20 08:12 UTC, merged