Add new interface for RCM
ginkgo-project/ginkgo pull request #1418
Opened 2023-10-10 09:15 UTC by upsj

This adds a new Permutation-based interface for the Reverse Cuthill-McKee (RCM) algorithm in line with the AMD and Nested Dissection algorithm. The old interface is deprecated.

Pulled out of #1408

2023-10-10 09:39 UTC, MarcelKoch requested changes
LGTM. IMO deprecating the old interface and adding a bit of documentation to the new interface is necessary.

2023-10-10 09:39 UTC, MarcelKoch commented on include/ginkgo/core/reorder/rcm.hpp
> + * @copydoc gko::reorder::Rcm
This needs some documentation for the difference with the current RCM

2023-10-10 09:39 UTC, MarcelKoch commented on include/ginkgo/core/reorder/rcm.hpp
> +    explicit Rcm(std::shared_ptr<const Executor> exec);
The old class needs to be marked as deprecated.

2023-10-10 09:39 UTC, MarcelKoch commented on core/reorder/rcm.cpp
> +    }
```suggestion
    using sparsity_mtx = matrix::SparsityCsr<float, IndexType>;
    std::unique_ptr<LinOp> converted;
    // extract row pointers and column indices
    IndexType* d_row_ptrs{};
    IndexType* d_col_idxs{};
    size_type d_nnz{};
    auto convert = [&](auto op, auto value_type){
        using ValueType = std::decay_t< decltype(value_type)>;
        using Identity = matrix::Identity<ValueType>;
        using Mtx = matrix::Csr<ValueType, IndexType>;
        using Scalar = matrix::Dense<ValueType>;
        auto conv_csr = matrix::Csr<ValueType, IndexType>::create(exec);
        as<Mtx>(op)->convert_to(conv_csr);
        if (!parameters_.skip_symmetrize) {
            auto scalar =
                initialize<Scalar>({one<ValueType>()}, exec);
            auto id = Identity::create(exec, conv_csr->get_size()[0]);
            // compute A^T + A
            conv_csr->transpose()->apply(scalar, id, scalar, conv_csr);
        }
        d_nnz = conv_csr->get_num_stored_elements();
        d_row_ptrs = conv_csr->get_row_ptrs();
        d_col_idxs = conv_csr->get_col_idxs();
        converted = std::move(conv_csr);        
    };
    if (auto convertible = dynamic_cast<const ConvertibleTo<matrix::Csr<float, IndexType>>*>(
            system_matrix.get())) {
        convert(system_matrix, float{});
    } else {
        convert(system_matrix, std::complex<float>{});
    }
```

2023-10-13 09:48 UTC, MarcelKoch approved these changes
LGTM. I guess rebasing is necessary.

2023-10-13 09:48 UTC, MarcelKoch commented on core/reorder/rcm.cpp
> +    auto const dim = adjacency_matrix->get_size();
```suggestion
    auto const dim = adjacency_matrix->get_size()[0];
```
after rebase

2023-10-13 09:48 UTC, MarcelKoch commented on core/test/reorder/rcm.cpp
> +#if defined(__GNUC__) || defined(__clang__)
The documentation on these pragmas is not very clear. I'm unsure how leaving out the corresponding `pop` effects warnings for other files. But, I would guess it doesn't affect those.

2023-10-13 10:20 UTC, pratikvn approved these changes
Some doc clarifications, but otherwise looks good.

2023-10-13 10:20 UTC, pratikvn commented on include/ginkgo/core/reorder/rcm.hpp
> + * Oak Ridge National Laboratory, 1994) is implemented here.
I think you should mention that the algorithm needs a symmetric matrix and that we have version that can explicitly symmetrize the matrix.

2023-10-13 11:30 UTC, yhmtsai commented
need pull request description

2023-10-29 20:10 UTC, upsj commented
format!

2023-10-30 02:39 UTC, merged