WIP Add pregenerated local solver as factory param
ginkgo-project/ginkgo pull request #1426
Opened 2023-10-13 20:10 UTC by greole

This PR adds a factory parameter to the schwarz preconditioner to pass in a fully generated solver.

2023-10-18 11:06 UTC, yhmtsai requested changes

2023-10-18 11:06 UTC, yhmtsai commented on core/distributed/preconditioner/schwarz.cpp
> +        this->local_solver_ = parameters_.generated_local_solver;
also add the set_solver like IR to fit the executor

2023-10-18 11:06 UTC, yhmtsai commented on test/mpi/preconditioner/schwarz.cpp
> +                 gko::InvalidStateError);
```suggestion
    auto schwarz_no_solver = prec::build().on(this->exec);

    ASSERT_THROW(schwarz_no_solver->generate(this->dist_mat),
                 gko::InvalidStateError);
```

2023-10-18 14:07 UTC, yhmtsai approved these changes

2023-10-18 14:17 UTC, pratikvn commented on include/ginkgo/core/distributed/preconditioner/schwarz.hpp
> +    void set_solver(std::shared_ptr<const LinOp> new_solver);
I think it does not need to be public.

2023-10-23 08:04 UTC, greole commented
format!

2023-10-23 08:42 UTC, yhmtsai commented
It also needs to rebase on the latest develop

2023-10-23 12:06 UTC, greole commented
rebase!

2023-10-24 06:02 UTC, merged