WIP: Add a Multilevel schwarz preconditioner
ginkgo-project/ginkgo pull request #1431
Opened 2023-10-15 13:25 UTC by pratikvn

This PR uses the distributed coarse level generation from PGM to use as a coarse level for the additive Schwarz preconditioner. The only requirement is that the galerkin product generator ($RAP$) generate a `multigrid::MultigridLevel` which is a triplet of `restrict`, `prolong` and `coarse` operators. The user additionally also needs to set the solver for the coarse level.

### TODO

+ [ ] Add options to switch between multiplicative and additive
+ [ ] Options for arbitrary number of levels. 

### Possible issues
1. The coarse level solve significantly reduces the number of iterations, but can be extremely expensive. Maybe makes sense to apply coarse solve, only a few times instead of every preconditioner apply (need to be careful of consistency of preconditioner apply) ? 
2. Weighting between the local solver solution and the coarse solution is unclear. 
3. Though the coarse solve and the local solve are independent, we have no way of performing them in parallel. This will probably require a rewrite of the apply interface to enable asynchronicity, in addition to support for multiple streams/queues.

2025-01-31 16:05 UTC, pratikvn commented
As a first step, I just added a two-level preconditioner with equal weighting for the local solution and the coarse solution. I think it maybe makes sense to try this out in some applications and then think about arbitrary number of levels, additive/multiplicative etc.

2025-01-31 16:06 UTC, pratikvn commented
format!

2025-02-03 09:57 UTC, MarcelKoch requested changes
Generally looks good, I left some minor nits.
Did you have a case, where the coarse grid solve was beneficial? Right now the provided example doesn't seem to benefit from the coarse grid solve.
Also, since the coarse and local solves are not computed in parallel, as you mentioned, which will probably be the case for a while, maybe implement it as a multiplicative version directly.

2025-02-03 09:57 UTC, MarcelKoch commented on include/ginkgo/core/distributed/preconditioner/schwarz.hpp
> +            galerkin_ops);
I'm not too convinced of the name and the doc. At least to me, `galerkin_ops` is too unspecific, maybe something like `coarse_level_factory` would be better suited. Also the doc should contain that this will be used to create a coarse level system, maybe 
```
Operator factory to generate the coarse system `A_c = R * A * P`. 
```

2025-02-03 09:57 UTC, MarcelKoch commented on core/distributed/preconditioner/schwarz.cpp
> +        prolong->apply(this->half_, csol_cache_.get(), this->half_, dense_x);
I don't think it's typical to weight these solutions. For example the book Domain Decomposition by Smith, Bjorstad, and Gropp, just sums all contributions up (p. 47) regardless of if they are from the subdomains, or the coarse grid.

2025-02-03 09:57 UTC, MarcelKoch commented on core/distributed/preconditioner/schwarz.cpp
> +    if (parameters_.galerkin_ops && parameters_.coarse_solver) {
maybe there should be an exception, if only one of those is set. I think that would be a configuration error, and the user should be notified.

2025-02-03 09:57 UTC, MarcelKoch commented on core/distributed/preconditioner/schwarz.cpp
> +                ->get_coarse_op()) {
Can this actually be null? If so, maybe that should be considered an error.

2025-02-03 09:57 UTC, MarcelKoch commented on core/distributed/preconditioner/schwarz.cpp
I think adjustments to the copy/move are necessary. However, they seem to be already incomplete as of now, so that might also be done in a separate PR.

2025-02-03 09:57 UTC, MarcelKoch commented on core/distributed/preconditioner/schwarz.cpp
> +            auto comm = coarse->get_communicator();
unused
```suggestion
```

2025-02-03 09:57 UTC, MarcelKoch commented on examples/distributed-solver/distributed-solver.cpp
> +    std::string schw_type = argc >= 5 ? argv[4] : "multi-level";
Just as a note, I was running this example with
```
mpirun -n 4 ./distributed-solver reference 10000 1000
```
and the `one-level` version was faster and used less iteration. So maybe it should be the default.

2025-02-14 09:34 UTC, pratikvn commented on core/distributed/preconditioner/schwarz.cpp
> +        prolong->apply(this->half_, csol_cache_.get(), this->half_, dense_x);
For multiplicative versions that is valid, but I think in this case it generally results in an over-correction and leads to solver divergence.

2025-02-14 09:41 UTC, pratikvn commented on core/distributed/preconditioner/schwarz.cpp
Tracking it here: https://github.com/ginkgo-project/ginkgo/issues/1779

2025-02-14 09:52 UTC, pratikvn commented on core/distributed/preconditioner/schwarz.cpp
> +    if (parameters_.galerkin_ops && parameters_.coarse_solver) {
I think we need in general a better way to validate our configuration. If multiple factory parameters, then I think there should be a way to communicate that directly to the user rather than having the logic in the core file. Maybe we can think about adding some dependency support checks in the factory parameter setup agnostic to the concrete class.

2025-02-14 10:02 UTC, MarcelKoch commented on core/distributed/preconditioner/schwarz.cpp
> +    if (parameters_.galerkin_ops && parameters_.coarse_solver) {
We could do that at a later point, but for now we should still throw if only one is set. I don't think it would be much of a burden here.

2025-02-14 10:56 UTC, pratikvn commented on examples/distributed-solver/distributed-solver.cpp
> +    std::string schw_type = argc >= 5 ? argv[4] : "multi-level";
Yes, it seems to depend on the problem size. I see that 100000 multi-level reduces the number of iterations, but it is slower. But I will change the default to one-level.

2025-02-17 09:02 UTC, pratikvn commented on core/distributed/preconditioner/schwarz.cpp
> +    if (parameters_.galerkin_ops && parameters_.coarse_solver) {
Yes, sure.

2025-03-17 14:11 UTC, MarcelKoch requested changes

2025-03-17 14:11 UTC, MarcelKoch commented on core/distributed/preconditioner/schwarz.cpp
> +    if (parameters_.coarse_weight > 0) {
I think a check for `coarse_weight > 1` wouldn't hurt.

2025-03-17 14:11 UTC, MarcelKoch commented on core/distributed/preconditioner/schwarz.cpp
> +            auto coarse = as<multigrid::MultigridLevel>(this->coarse_level_)
you could use `if(auto coarse_level = std::dynamic_pointer_cast<const multigrid::MultigridLevel>(this->coarse_level_))` to remove redundancy.

2025-03-18 10:05 UTC, pratikvn commented on core/distributed/preconditioner/schwarz.cpp
> +            auto coarse = as<multigrid::MultigridLevel>(this->coarse_level_)
IMO, the current one is easier to understand.

2025-03-18 10:10 UTC, MarcelKoch requested changes

2025-03-18 10:10 UTC, MarcelKoch commented on core/distributed/preconditioner/schwarz.cpp
> +    if (auto& obj = config.get("coarse_level")) {
all config parameters are missing tests.

2025-03-18 13:11 UTC, yhmtsai requested changes
#1806 seems to be merged first. We will need to discuss the two-level should take the matrix after or before $\ell_1$ modification.

2025-03-18 13:11 UTC, yhmtsai commented on core/distributed/preconditioner/schwarz.cpp
> +            {ValueType{1} - ValueType{parameters_.coarse_weight}},
because we only use it in ValueType, the type of coarse_weight should directly use ValueType not double

2025-03-18 13:11 UTC, yhmtsai commented on core/distributed/preconditioner/schwarz.cpp
> +            // Cannot guarantee that coarse op is not nullptr
should it throw the error rather than make the operation silent?

2025-03-18 13:11 UTC, yhmtsai commented on examples/distributed-solver/distributed-solver.cpp
> +    // - One-level or two-level preconditioner, defaults to one-level.
it also has another option for no-preconditioned in the code

2025-03-18 13:11 UTC, yhmtsai commented on core/distributed/preconditioner/schwarz.cpp
>                                     gko::detail::get_local(dense_x));
I think you can move the local_solver part to the beginning without another condition.
```
if (local_solver_ != nullptr) {...}
if (this->coarse_solver_ ...) {...}
```

2025-03-18 13:18 UTC, yhmtsai commented on include/ginkgo/core/distributed/preconditioner/schwarz.hpp
> +         * (when the coarse weight is < 0). A weighting can instead be provided
```suggestion
         * (when the coarse weight is < 0 or > 1). A weighting can instead be provided
```

2025-03-18 13:20 UTC, yhmtsai commented on core/distributed/preconditioner/schwarz.cpp
> +            {ValueType{1.0}}, this->get_executor());
putting coarse_weight = 1 or 0 to the above formula will not get the same weight here, right?

2025-03-24 13:45 UTC, pratikvn commented on core/distributed/preconditioner/schwarz.cpp
> +            {ValueType{1.0}}, this->get_executor());
Yes, coarse_weight 1 should mean that only the coarse level solve is used, and coarse_weight 0 means that only the local solves are used. If no coarse_weight is used (implying to weighting between two solutions), then the solutions are just added up.

2025-03-24 13:46 UTC, pratikvn commented on core/distributed/preconditioner/schwarz.cpp
>                                     gko::detail::get_local(dense_x));
I prefer to keep them in separate code paths for better code readability.

2025-03-24 13:52 UTC, yhmtsai commented
`pgm_factory` and `coarse_solver_factory` are not initialized

2025-03-24 14:18 UTC, pratikvn commented on core/distributed/preconditioner/schwarz.cpp
> +            // Cannot guarantee that coarse op is not nullptr
I guess that depends on whether we consider generation of a coarse level valid with empty triplet (R, A, P = nullptr)

2025-03-24 19:55 UTC, pratikvn commented
Regarding the L1 smoother, I think it should not affect the coarse solve. The levels (fine-local and coarse) should still be generated from the input matrix rather than an implicitly modified matrix. 

IMO, the L1 smoother should have been separate from Schwarz class and not included in the Schwarz class at all. It should be equivalent to the user calling `diag_mat->apply(one, I, one, dist_mat)`, right (After summing the non-local matrix rows) ? I am not entirely sure if it should be a part of the Schwarz preconditioner class directly. I think that makes sense for the Jacobi preconditioner, but I am not sure it makes sense for the other preconditioners ?

2025-03-26 14:19 UTC, yhmtsai commented
for L1, yes it is equivalent. However, user will not be able to handle it in adding the additional computation by themselves because it should only be used in the preconditioner. the solver will not adapt the process.

2025-03-26 14:21 UTC, MarcelKoch approved these changes

2025-03-26 14:21 UTC, MarcelKoch commented on core/distributed/preconditioner/schwarz.cpp
> +        if (this->local_solver_ != nullptr) {
nit: else if (...)

2025-03-26 14:21 UTC, MarcelKoch commented on core/distributed/preconditioner/schwarz.cpp
> +        if (as<multigrid::MultigridLevel>(this->coarse_level_)) {
This can only return false, if `coarse_level_` has dynamic type `MultigridLevel`, but is the nullptr. Can this actually happen? If it doesn't have the correct dynamic type, then `as` will already throw an exception.

2025-03-27 09:02 UTC, yhmtsai commented on core/distributed/preconditioner/schwarz.cpp
> +        if (as<multigrid::MultigridLevel>(this->coarse_level_)) {
I assume you mean only return true?

2025-03-27 09:04 UTC, yhmtsai commented on core/distributed/preconditioner/schwarz.cpp
> +            // Cannot guarantee that coarse op is not nullptr
I think we should throw an error now. The previous issue here is caused by that the test does not initialize the coarse solver and coarse level properly. The slight operation on this will give user wrong performance thought. If someone comes to use for this behavior later, we can add another parameter for that but not the default behavior.

2025-03-27 09:06 UTC, yhmtsai commented on include/ginkgo/core/distributed/preconditioner/schwarz.hpp
> +         * (when the coarse weight is < 0 or > 1). A weighting can instead be
```suggestion
         * (when the coarse weight is <= 0 or > 1). A weighting can instead be
```

2025-03-27 09:11 UTC, yhmtsai commented on core/distributed/preconditioner/schwarz.cpp
> +            {ValueType{parameters_.coarse_weight}}, this->get_executor());
```suggestion
            {static_cast<ValueType>(parameters_.coarse_weight)}, this->get_executor());
```
there is narrow-down warning here

2025-03-27 09:12 UTC, yhmtsai commented on core/distributed/preconditioner/schwarz.cpp
> +            {ValueType{1.0}}, this->get_executor());
```suggestion
            {one<ValueType>()}, this->get_executor());
```
same for next one to avoid the narrow-down warning.

2025-03-27 09:13 UTC, yhmtsai commented on include/ginkgo/core/distributed/preconditioner/schwarz.hpp
>          bool GKO_FACTORY_PARAMETER_SCALAR(l1_smoother, false);
add a comment about it is unsupported with two level

2025-03-27 09:14 UTC, yhmtsai commented on include/ginkgo/core/distributed/preconditioner/schwarz.hpp
> +         * (when the coarse weight is < 0 or > 1). A weighting can instead be
changing the condition in the core might be better for symmetric

2025-03-27 09:25 UTC, yhmtsai commented on test/mpi/preconditioner/schwarz.cpp
> +TYPED_TEST(SchwarzPreconditioner, CanApplyMultilevelPreconditioner)
The test is not enough because it does not verify the result based on something we tested before.
You can do the workflow again like you did in core. also need two coarse weight testcase: one is in the [0, 1] and the other is default.

I was thinking whether extracting the same thing from core to here is considered valid or not.
It seems to be duplication but the routines here can be considered verified by the other tests.

2025-03-27 09:27 UTC, MarcelKoch commented on core/distributed/preconditioner/schwarz.cpp
> +        if (as<multigrid::MultigridLevel>(this->coarse_level_)) {
No, but the first comma is confusing, so I remove it.

2025-04-07 19:56 UTC, pratikvn commented on core/distributed/preconditioner/schwarz.cpp
> +            // Cannot guarantee that coarse op is not nullptr
No, the issue is that when pgm (or MultigridLevel) is generated with an empty matrix, then the coarse op is null. We should probably ensure that the triplet generated by MultigridLevel cannot be null. If we throw here then it means that the Schwarz preconditioner will not be in a valid state.

2025-04-07 20:16 UTC, pratikvn commented on include/ginkgo/core/distributed/preconditioner/schwarz.hpp
>          bool GKO_FACTORY_PARAMETER_SCALAR(l1_smoother, false);
It is supported with two-level. L1 being a local smoother is separate from the coarse solve.

2025-04-07 20:19 UTC, pratikvn commented on test/mpi/preconditioner/schwarz.cpp
> +TYPED_TEST(SchwarzPreconditioner, CanApplyMultilevelPreconditioner)
Which core tests do you mean ? I dont think there are any tests in core which do a proper apply.

2025-04-10 08:42 UTC, pratikvn commented on test/mpi/preconditioner/schwarz.cpp
> +TYPED_TEST(SchwarzPreconditioner, CanApplyMultilevelPreconditioner)
Should be updated now. I just use Multigrid as a preconditioner to emulate the coarse apply and a local precond separately and then add the solutions together.

2025-04-10 09:04 UTC, yhmtsai requested changes

2025-04-10 09:04 UTC, yhmtsai commented on core/distributed/preconditioner/schwarz.cpp
> +        }
throw an error or assert if coarse_level_ or coarse_solver are nullptr.
Do you need the fallback option? 
For example, the problem is small enough or different reason such that multigrid level does not generate proper one.
User seems to easily have a wrong expectation. we do not perform the two-level schwarz.

2025-04-10 09:04 UTC, yhmtsai commented on core/distributed/preconditioner/schwarz.cpp
> +                                   gko::detail::get_local(dense_x));
you need to wrap if (this->local_solver) to ensure it is not nullptr

2025-04-10 10:56 UTC, pratikvn commented on core/distributed/preconditioner/schwarz.cpp
> +                                   gko::detail::get_local(dense_x));
I will add an assert in the generate.

2025-04-10 12:12 UTC, pratikvn commented on core/distributed/preconditioner/schwarz.cpp
> +        }
I would say that is out of scope of what Schwarz should do. I think the user has to ensure that the coarse level has valid inputs. The fallback option will be that there is no coarse level solve.

2025-04-11 07:38 UTC, merged