Use native CMake variables for compiler flags
ginkgo-project/ginkgo pull request #1535
Opened 2024-01-18 21:02 UTC by upsj

Pulled out of #1334, this uses the natively supported `CMAKE_<LANG>_FLAGS` variables instead of our custom variables and sets them in CI instead of CMake, which is discouraged in its genericity, since `-Wpedantic` is only supported in gcc-like compilers

TODO:
- [ ] update README instructions for SYCL

2024-01-19 08:00 UTC, MarcelKoch reviewed
I guess we could think about adding cmake presets. That would be an easy way to keep the `-Wpedantic`. I was already looking into that, so I will get something ready for discussion.

2024-01-19 08:09 UTC, upsj commented on CMakeLists.txt
> -set(GINKGO_CUDA_COMPILER_FLAGS "" CACHE STRING
There is no native equivalent until we tackle #1334

2024-01-19 08:12 UTC, upsj commented on dpcpp/CMakeLists.txt
> -target_compile_options(ginkgo_dpcpp PRIVATE "${GINKGO_COMPILER_FLAGS}")
I was considering it, but that could lead to weird situations where some math functions might have two different definitions depending on whether they are compiled as part of `libginkgo_dpcpp.so` or from `ginkgo/core/base/math.hpp`.

2024-01-22 12:45 UTC, MarcelKoch requested changes

2024-01-22 12:45 UTC, MarcelKoch commented on reference/get_info.cmake
> +#ginkgo_print_module_footer(${detailed_log} "")
Uncomment?

2024-01-22 12:45 UTC, MarcelKoch commented on omp/get_info.cmake
> +#ginkgo_print_module_footer(${detailed_log} "OMP variables:")
same?

2024-02-05 12:46 UTC, MarcelKoch approved these changes

2024-02-14 02:43 UTC, thoasm approved these changes
Looks good to me!

2024-02-14 11:13 UTC, merged