Add row and col scaling functions to distributed matrix
ginkgo-project/ginkgo pull request #1640
Opened 2024-07-03 12:17 UTC by fritzgoebel

This PR adds a `row_scale` and a `col_scale` function to the distributed matrix. This functionality is needed in openCARP.

- The row scaling is straight forward, with a distributed vector of scaling coefficients that has the same row partitioning as the matrix, we can just scale the rows of local and non-local matrices with the local vectors.
- For column scaling, we need to communicate the non-local scaling coefficients to scale the columns of the non-local matrices. This can be simply done with the matrix's `communicate`.

2024-07-03 12:33 UTC, MarcelKoch approved these changes
LGTM. That is a lot simpler than I expected.

2024-07-03 13:31 UTC, yhmtsai approved these changes

2024-07-04 12:43 UTC, upsj requested changes
This seems to assume that the scaling factors have unit stride - that's not necessarily true

2024-07-09 10:46 UTC, MarcelKoch approved these changes

2024-07-11 12:36 UTC, upsj approved these changes

2024-07-11 12:36 UTC, upsj commented on test/mpi/matrix.cpp
> +    GKO_ASSERT_EQ(col_scaling_factors->get_stride(), 2);
```suggestion
    ASSERT_EQ(col_scaling_factors->get_stride(), 2);
```

2024-07-11 12:36 UTC, upsj commented on test/mpi/matrix.cpp
> +    GKO_ASSERT_EQ(row_scaling_factors->get_stride(), 2);
```suggestion
    ASSERT_EQ(row_scaling_factors->get_stride(), 2);
```

2024-07-19 12:07 UTC, merged