Fix issues with distributed preconditioners, add to benchmarks
ginkgo-project/ginkgo pull request #1660
Opened 2024-08-05 08:45 UTC by pratikvn

This PR adds benchmarking support for distributed preconditioners. It also fixes a few things that were causing increased allocations for distributed preconditioners.

2024-08-05 10:36 UTC, greole commented on core/solver/multigrid.cpp
> +    using ws = workspace_traits<Multigrid>;
unused?

2024-08-06 09:51 UTC, yhmtsai requested changes
could you separate the pr to two? benchmark and the rest.

2024-08-06 09:51 UTC, yhmtsai commented on benchmark/utils/preconditioners.hpp
> +              "");
```suggestion
              );
```

2024-08-06 09:51 UTC, yhmtsai commented on benchmark/utils/preconditioners.hpp
> +                                    .with_deterministic(FLAGS_mg_deterministic))
these flag are not available yet

2025-05-16 12:14 UTC, pratikvn commented
Closed in favour of #1844 and #1845

2025-05-16 12:14 UTC, closed without merging