add yaml-cpp support for file config
ginkgo-project/ginkgo pull request #1677
Opened 2024-09-11 03:28 UTC by yhmtsai

This PR adds the yaml-cpp to support yaml format for file config which gives the alias feature to reuse config.
welcome any suggestion of yaml library.

2024-09-11 08:04 UTC, MarcelKoch commented
Regarding the library choice, yaml-cpp seems to be the most popular, but [rapidyaml](https://github.com/biojppm/rapidyaml) seems to be a good alternative. rapidyaml supports resolving anchors automatically, which would simplify our parse implementation (see [here](https://rapidyaml.readthedocs.io/latest/doxygen/group__doc__quickstart.html#ga2dd6afea118e691dff0439a4c60036fb)).

2025-02-13 13:42 UTC, MarcelKoch requested changes
LGTM, only few minor points

2025-02-13 16:14 UTC, yhmtsai commented on include/ginkgo/extensions/config/yaml_config.hpp
> + * know which entry is the actual solver, so please use the parse_yaml function.
for example, like alias.yml
```
base: &base_config
  key1: 123
test:
  << [*base_config]
  key3: true
```
if user only parses the file without specify the entry, I do not know `base` or `test` should be the solver to parse.
they need to do `parse_yaml(yaml["test"])` to point out the `test` is the solver.

2025-02-13 16:20 UTC, yhmtsai commented on include/ginkgo/extensions/config/yaml_config.hpp
> + * know which entry is the actual solver, so please use the parse_yaml function.
I also add it into comment

2025-02-13 16:25 UTC, MarcelKoch approved these changes

2025-02-18 13:28 UTC, upsj approved these changes
LGTM!

2025-02-18 13:28 UTC, upsj commented on include/ginkgo/extensions/config/yaml_config.hpp
> +        for (YAML::const_iterator it = map.begin(); it != map.end(); ++it) {
nit: this can probably be written as a range-for loop with structured bindings?

2025-02-19 10:02 UTC, upsj commented
I wish there was a better library for YAML parsing, but I guess this will have to do. There are some issues with how yaml-cpp handles assignment and copies https://github.com/jbeder/yaml-cpp/issues/1275. And to quote the developer:
> Unfortunately, I don't have time to work on this library any more

Not blocking, just something to keep in mind in case we find a better library out there.

2025-02-19 10:33 UTC, yhmtsai commented
Yes, I also faced the issue that it still accepts the invalid yaml file.
like
```
arr: &arr1 [1, 2, 3]
base:
  <<: *arr1
```
which should be invalid because <<: can only used from map not array.
it accepts this file unfortunately.
As @MarcelKoch mentioned, rapidyaml might be another good library to use.
yaml-cpp still served larger group, so I will still merge this first.
Because config is not tied to any specific parse, we can create rapidyaml extension for config later

2025-02-19 14:46 UTC, merged