Add function to create gko::config::pnode from std::string
ginkgo-project/ginkgo pull request #1721
Opened 2024-11-05 08:21 UTC by greole

This PR adds a function to create `gko::config::pnode` directly from a `std::string`.

Motivation: We would like to use Ginkgo's file config solver within the pyGinkgo bindings. The current implementation of the config solver seems to rely on json files. However, creating temporary files is a nuisance which can cause all kinds issues and is not really necessary in our case.  Thus, just passing a `std::string`  to generate a property tree would simplify things a lot.

2024-11-05 08:24 UTC, upsj approved these changes
LGTM, I thought we had this already

2024-11-05 08:24 UTC, upsj commented on include/ginkgo/extensions/config/json_config.hpp
> +inline gko::config::pnode parse_json_string(std::string json)
I wonder if it's a good time to start introducing `std::string_view` to the code base, now that we support C++17

2024-11-05 09:50 UTC, yhmtsai requested changes
need to add a test for it in extensions/test/json_config
question for pyGinkgo:
do you have any intermediate layer in C or C++ between ginkgo and pyGinkgo?

2024-11-05 10:31 UTC, greole commented
> need to add a test for it in extensions/test/json_config

sure i'll add one

> question for pyGinkgo:
> do you have any intermediate layer in C or C++ between ginkgo and pyGinkgo?

we use pybind11 , which is c++, to generate any intermediate code to register to python.

2024-12-05 09:53 UTC, yhmtsai approved these changes

2024-12-05 13:10 UTC, merged