Run Intel CI jobs on cluster
ginkgo-project/ginkgo pull request #1723
Opened 2024-11-07 17:03 UTC by upsj

This runs intel CI jobs on the new `gitlab-meta-runner`-driven runners on the cluster

2024-11-11 09:20 UTC, yhmtsai requested changes
I notice you also change some nvidia-gpu jobs, and we are missing cuda 11.0 which is our oldest nvidia compiler support.
Could you also add them back?

2024-11-11 09:21 UTC, upsj commented on .gitlab/image.yml
> +    - intel-gpus
Right now, everything is running on PVC, A770 will get a separate tag

2024-11-11 09:21 UTC, upsj commented on .gitlab/image.yml
> +    - nvidia-old-gpus
old-gpus means <= SM 8.0, because of CUDA 11.0 support

2024-11-11 09:22 UTC, upsj commented on examples/CMakeLists.txt
> +            set_property(TEST example_${example}_${executor} PROPERTY ENVIRONMENT OMP_NUM_THREADS=4)
I think the examples are fast enough to not need it. Only with OpenMP I saw parallel examples taking 500s to executing, so this is a simple workaround

2024-11-11 12:28 UTC, upsj commented on .gitlab/variables.yml
>      BUILD_PAPI_SDE: "OFF"
I had some some issues with HWLOC missing from published containers, but maybe that was outdated files on FTP. I'll run it again with the change reverted.

2024-11-11 12:55 UTC, upsj commented on .gitlab/variables.yml
>      BUILD_PAPI_SDE: "OFF"
Seems like that issue was a fluke, I removed the changes

2024-11-11 22:18 UTC, upsj commented on .gitlab/image.yml
> +    - nvidia-old-gpus
Removing the CUDA-related changes for now

2024-11-12 09:02 UTC, yhmtsai approved these changes
LGTM. only a nit on the job name

2024-11-15 08:59 UTC, MarcelKoch approved these changes

2024-11-16 21:05 UTC, merged