Master release/1.9.0
ginkgo-project/ginkgo pull request #1748
Opened 2024-12-09 16:16 UTC by MarcelKoch

This PR updates `master` to the latest state of develop. This is done by cherry-picking all commit between the v1.8.0 and v1.9.0 release, using:
```bash
git log --format=%H --no-merges --skip=1 --reverse <prev-release>..v1.9.0 | git cherry-pick --stdin
```
The commit for `<prev-release>` was found using:
```bash
git log --oneline --merges --first-parent --skip=1 -n 1 v1.9.0
```
In future releases, this should not be necessary, as the release tags can just be used directly.

2024-12-09 16:47 UTC, upsj commented
Would using `git merge` be an option? The worktree should look exactly the same as `main`, so merging should be possible.

2024-12-09 16:49 UTC, MarcelKoch commented
No, `master` and `main` don't have a common history since the 1.0 release. So merging `main` into master would introduce ~6000 commits.

2024-12-10 10:35 UTC, yhmtsai commented
JOSS is failed due to old upload artifact.

2024-12-10 10:42 UTC, pratikvn commented
I think we can ignore the joss pandoc job for this and main branch. I think we can remove that job entirely in develop. I guess currently it has been setup to run on master and also on main somehow in the settings, which can probably be updated.

2024-12-10 15:29 UTC, pratikvn approved these changes

2025-01-11 13:48 UTC, upsj requested changes
There seem to be some minor changes missing, e.g. version numbers in `examples`, see 
```bash
git diff origin/master-release/1.9.0 origin/main --word-diff --word-diff-regex=.
```

2025-01-14 08:17 UTC, MarcelKoch commented
@upsj should be fixed now.

2025-02-14 08:07 UTC, upsj approved these changes

2025-02-18 08:41 UTC, merged