Add cmake-format, and a pre-commit hook for it
ginkgo-project/ginkgo pull request #1755
Opened 2024-12-15 11:49 UTC by pratikvn

This PR adds a pre-commit hook to format CMakeLists,txt files. The actual format can still be discussed. But currently, I just formatted all CMakeLists.txt files with the default style. If necessary, we can adjust the style in the `.cmake-format,json` file.

2024-12-15 12:19 UTC, upsj approved these changes
LGTM! Format suggestions:

2024-12-15 12:19 UTC, upsj commented on .cmake-format.json
> +    "dangle_parens": false,
This option would make for nicer diffs e.g. when adding files to the end of a list

2024-12-15 12:19 UTC, upsj commented on .cmake-format.json
> +    "tab_size": 2,
Maybe keep this in sync with our C++ code?
```suggestion
    "tab_size": 4,
```

2024-12-15 12:19 UTC, upsj commented on .cmake-format.json
> +    },
Here we should list the functions that use CMake argument parsing

2024-12-16 02:04 UTC, yhmtsai requested changes

2024-12-16 02:04 UTC, yhmtsai commented on cmake/install_helpers.cmake
> +# @param name  the name of the target @param ARGN  any external dependencies
wrong format

2024-12-16 02:04 UTC, yhmtsai commented on core/CMakeLists.txt
> +# MSVC: LNK1189 issue CLANG in MSYS2 (MINGW): too many exported symbols We
wrong format

2025-02-13 11:45 UTC, yhmtsai commented
alternative one is https://github.com/BlankSpruce/gersemi

2025-02-13 14:26 UTC, pratikvn commented
Gersemi is used now, as it also seems to provide a decent setup and has pre-commit support, in addition to being active. The comments needed to be guarded with `#gersemi: on/off`, but otherwise, the default formatting seems to work well enough.

2025-02-13 14:28 UTC, upsj commented
Is there a way to prevent that from happening? Comments are a pretty important and frequent part of the code, and other formatters manage to not mess them up that badly 😁

2025-02-13 14:32 UTC, pratikvn commented
Not all comments, but only the ones where we try to use multi-line doxygen style documentation comments.

2025-02-13 14:38 UTC, pratikvn commented
Turns out it is doing the right thing anyway, so disabling it with `off/on` is not necessary.

2025-02-17 07:45 UTC, pratikvn commented on third_party/identify_stream_usage/CMakeLists.txt
> +            ON
Yes, I moved it above now.

2025-02-17 07:49 UTC, pratikvn commented on cmake/CTestScript.cmake
> +    )
I think it does not break single argument into multiple lines. It was the same before as well, so I think it should be okay.

2025-02-17 08:07 UTC, yhmtsai approved these changes

2025-02-18 12:00 UTC, merged