enable Half in mpi
ginkgo-project/ginkgo pull request #1759
Opened 2024-12-30 16:01 UTC by yhmtsai

This PR enables half precision in distributed environment by adding custom operation.

one-side operation like accumulation and fetch_and_op does not support custom operation.

Note. Newer version of mpi might support half precision natively (also for one-side operation) if the administrator build it with compiler supporting native half precision and enable the option.

TODO:
- [ ] enable the rest distributed function with half
- [ ] put the custom operation in gko::comm?

2025-01-09 10:02 UTC, MarcelKoch requested changes
I'm mainly concerned about using device buffers for the custom operations, and maybe moving the operations into a private header.

2025-01-10 09:13 UTC, yhmtsai commented on include/ginkgo/core/base/mpi.hpp
> +inline void sum(void* input, void* output, int* len, MPI_Datatype* datatype)
I have the same concern.
However, I think mpi will not use device memory to handle the reduction operation. Even in frontier, they have additional unit to handle not use gpu to sum cross nodes.

2025-01-10 09:17 UTC, yhmtsai commented on include/ginkgo/core/distributed/vector.hpp
> +    mpi::op_manager norm_sum_op_;
I have tried the static variable already but it did not work out.
We call MPI_finalize to finish, but the static variable will be destroyed when the process leave main scope, which is after MPI_finalize and MPI complains that.

2025-01-13 12:01 UTC, MarcelKoch commented on include/ginkgo/core/distributed/vector.hpp
> +    mpi::op_manager norm_sum_op_;
I tried some simple benchmarking of creating/freeing the MPI_Op, and it seems to not scale with the number of processes. I guess that is to be expected, as it is not a collective operation. So I would suggest to just create the ops on-the-fly when necessary.

2025-01-13 12:03 UTC, MarcelKoch commented on include/ginkgo/core/base/mpi.hpp
> +inline void sum(void* input, void* output, int* len, MPI_Datatype* datatype)
BTW here is the benchmark: https://gist.github.com/MarcelKoch/cbbee408bbd4d53689ef6b7aad404b04

2025-01-13 12:03 UTC, MarcelKoch commented on include/ginkgo/core/distributed/vector.hpp
> +    mpi::op_manager norm_sum_op_;
BTW here is the benchmark: https://gist.github.com/MarcelKoch/cbbee408bbd4d53689ef6b7aad404b04

2025-01-13 12:18 UTC, yhmtsai commented on include/ginkgo/core/distributed/vector.hpp
> +    mpi::op_manager norm_sum_op_;
thanks for profiling! just to be sure, you mean the runtime is not scale with the number of processes, right?

2025-01-13 12:40 UTC, MarcelKoch commented on include/ginkgo/core/distributed/vector.hpp
> +    mpi::op_manager norm_sum_op_;
Yes, it has a fixed overhead that doesn't depend on the number of processes.

2025-01-13 17:19 UTC, yhmtsai commented on include/ginkgo/core/distributed/vector.hpp
> +    // For distributed case, next<next<V>> will be V in the candicated list.
yes.
I do not think so because Dense will use https://github.com/ginkgo-project/ginkgo/blob/b18607efa7354daf942c05a03cdf921f24deed59/include/ginkgo/core/base/temporary_conversion.hpp#L102 to call `create(exec)` function and `Dense` can `convert_to` itself, which satisfies the `enable_if` condition.

2025-01-16 11:27 UTC, MarcelKoch commented on common/cuda_hip/distributed/assembly_kernels.cpp
> +GKO_INSTANTIATE_FOR_EACH_VALUE_AND_LOCAL_GLOBAL_INDEX_TYPE(
The base version of that macro is now unused.

2025-01-22 10:01 UTC, pratikvn approved these changes
Some `using ...` statements are unused, but otherwise LGTM!

2025-02-12 09:02 UTC, yhmtsai commented on core/test/mpi/base/bindings.cpp
> +}
I only implement `min` here because we currently only use it here.

2025-02-13 11:47 UTC, yhmtsai commented on common/cuda_hip/distributed/assembly_kernels.cpp
> +GKO_INSTANTIATE_FOR_EACH_VALUE_AND_LOCAL_GLOBAL_INDEX_TYPE(
I use base and the normal one is built on the base one.

2025-02-13 11:52 UTC, yhmtsai commented on include/ginkgo/core/base/mpi.hpp
> +GKO_REGISTER_MPI_TYPE(std::complex<half>, MPI_FLOAT);
I have discussed it with @MarcelKoch . I think we will go for the custom implementation now, then later we might check whether to do native support. I had tried something in https://github.com/ginkgo-project/ginkgo/pull/1759/commits/deb12f05358de22fcb6aef02480584a8a320ee1c and it already shows it quite not consistent between OpenMPI and MPICH

2025-02-13 14:12 UTC, MarcelKoch requested changes
LGTM, only two small nits left.

2025-02-13 14:12 UTC, MarcelKoch commented on core/mpi/mpi_op.hpp
> +// ginkgo custom mpi sum operation impelementation
nit:
```suggestion
// ginkgo custom mpi sum operation implementation
```

2025-02-13 14:12 UTC, MarcelKoch commented on core/mpi/mpi_op.hpp
> +using op_manager = std::shared_ptr<MPI_Op>;
yes, that looks like a good approach.

2025-02-13 14:12 UTC, MarcelKoch commented on core/test/utils.hpp
>  using ValueLocalGlobalIndexTypesBase =
still not used

2025-02-13 14:52 UTC, yhmtsai commented on core/test/utils.hpp
>  using ValueLocalGlobalIndexTypesBase =
ah, I thought this is also the macro. it is removed now.

2025-02-19 10:53 UTC, merged