Fix Coo out of bounds access for strided vectors
ginkgo-project/ginkgo pull request #807
Opened 2021-06-30 14:40 UTC by upsj

This PR prevents the Coo CPU kernels from overwriting data past the end of the vector, since they took the amount of storage, not the actual number of elements into account.

2021-06-30 14:43 UTC, MarcelKoch commented
This change seems necessary, but just out of curiosity, have you looked at the performance impact of this? My guess is that it would be a bit slower for single right-hand sides.

2021-06-30 14:49 UTC, upsj commented
Yes, all of these kernels would profit heavily of specialization for single RHS, but that is the topic for another PR. The performance would probably make too much of a difference, since the previous version involves integer divisions, which the compilers seemed to have issues with before.

2021-06-30 14:55 UTC, yhmtsai requested changes
omp initial/scale can be replaced by dense::fill or dense::scale.
Could you also add the corresponding test to cuda/hip?

2021-06-30 14:55 UTC, yhmtsai commented on omp/matrix/coo_kernels.cpp
>      }
you can also use the dense::fill for it

2021-06-30 14:55 UTC, yhmtsai commented on omp/matrix/coo_kernels.cpp
>      }
dense::scale

2021-07-01 07:52 UTC, yhmtsai approved these changes
LGTM. one question about the apply output object

2021-07-01 07:52 UTC, yhmtsai commented on cuda/test/matrix/coo_kernels.cpp
> +    dmtx->apply(dy.get(), dresult.get());
should it be dresult_padded? also for others?

2021-07-01 08:13 UTC, pratikvn approved these changes
LGTM!

2021-07-01 11:57 UTC, merged