Scalar Jacobi specialization and kernels
ginkgo-project/ginkgo pull request #808
Opened 2021-06-30 16:53 UTC by pratikvn

This PR adds special kernels for the scalar Jacobi preconditioner. It extracts the diagonal from the system matrix and applies the inverse of the diagonal to the rhs. The generate and apply overhead compared to the usual block-Jacobi should be lesser due to fewer storage requirements and memory movement in general.

This should in combination with the `Ir` solver, provide for some cheap and effective relaxation methods, useful in multi-grid and coarse grid solvers.

2021-06-30 17:15 UTC, upsj requested changes
LGTM in general, this makes for a really neat interface :)
Only two specific things come to my mind:
1. do we need to do something special for 0 diagonal entries? Maybe set them to 1 (implicitly)? Maybe we should consider the same for singular blocks (setting them to the identity matrix)?
2. I would prefer if we could reuse the existing data structures to avoid complicating the value semantics of the objects, see #753. Basically ´Array` does the right thing, while `std::shared_ptr` doesn't respect executors, which can cause issues when copying around `Jacobi` objects.

2021-06-30 17:15 UTC, upsj commented on omp/preconditioner/jacobi_kernels.cpp
> +    for (size_type i = 0; i < x->get_size()[0]; ++i) {
This would be a prime candidate for #733 :)

2021-06-30 17:15 UTC, upsj commented on include/ginkgo/core/preconditioner/jacobi.hpp
> +    std::shared_ptr<matrix::Diagonal<value_type>> diag_;
How about reusing the `blocks` array instead? This avoids a few issues related to copy/move_to

2021-06-30 17:15 UTC, upsj commented on hip/test/preconditioner/jacobi_kernels.cpp
> +TEST_F(Jacobi, HipScalarLinearCombinationApplyEquivalentToRef)
Can you try using different non-default strides for the two vectors?

2021-07-01 11:33 UTC, upsj approved these changes

2021-07-01 12:58 UTC, hartwiganzt approved these changes
LGTM.
There is no test whether this kernel is invoked when the BS is set to 1, or did I miss that?

2021-07-01 13:08 UTC, pratikvn commented
@hartwiganzt, I tested that manually by printing from within the newly added kernels.

2021-07-02 09:00 UTC, pratikvn commented
rebase!

2021-07-02 09:05 UTC, merged