Strategy to switch between Dense kernels in Ginkgo
ginkgo-project/ginkgo pull request #967
Opened 2022-02-08 07:14 UTC by pratikvn

This PR adds a strategy enum to allow runtime switching between vendor and Ginkgo provided kernels. 

+ Is not kernel specific, but Dense object specific.
+ `create_with_config_of` and `create_with_type_of` set the same strategy as their parent.
+ Strategies of objects created within Ginkgo cannot be controlled, but set to default, which is currently using Ginkgo kernels.

This is still a WIP. Only `dot` has been implemented as a prototype. You can see how it works in the cuda/hip dense kernel tests.

2022-02-08 08:04 UTC, upsj commented
What is the purpose of this strategy approach? From the user side, I mainly care about performance and correctness. Opposite to Csr, both of those are not really data-dependent, as the only data with performance impact are the matrix dimensions/stride.
If we want to use the vendor libraries for #rhs = 1, why don't we do it on the kernel side?
If this is about benchmarking, we can add hipBLAS/cuBLAS wrappers to the BLAS benchmark like we did for Csr.

2022-02-08 08:05 UTC, Slaedr requested changes
The general idea makes sense. However, I think we, and users, may want to use different strategies (I guess they're really blas-backends or something) for different operations. See my comments below.

2022-02-08 08:05 UTC, Slaedr commented on include/ginkgo/core/matrix/dense.hpp
> +    strategy_type strategy_{strategy_type::gko};
Are you sure we want to have only one strategy type for the entire class `Dense`? What if someone wants gko norm2 and vendor dot? Or we might add the option of vendor apply (once Vector is separated from Dense), and then that leads to even more options. Unless there's a better solution, I'd suggest
```suggestion
    strategy_type dot_strategy_{strategy_type::gko};
    strategy_type norm2_strategy_{strategy_type::gko};
```
and so on.

2022-02-08 08:05 UTC, Slaedr commented on reference/matrix/dense_kernels.cpp
> +    for (size_type j = 0; j < x->get_size()[1]; ++j) {
Haha, this is funny. Can we just optionally link to Netlib blas and call that routine here instead? If we don't find a system Blas, we could leave this unimplemented. For testing, we already have `compute_dot` to compare against.

2022-02-08 08:05 UTC, Slaedr commented on include/ginkgo/core/matrix/dense.hpp
> +          strategy_(strategy)
If we accept my suggestion on multiple strategies, we could copy this argument to all strategies, and provide another constructor that takes all the individual strategies.

2022-02-08 08:09 UTC, Slaedr commented
@upsj You make a good point; we could go that way too. But if the idea is to give the user choice of blas backend, I'm for that as well. From time to time, we or the vendor might introduce improvements that might change the calculus for the user. We may not be able to or want to react to changes from the vendor side quickly enough.

2022-02-10 21:32 UTC, pratikvn commented on cuda/matrix/dense_kernels.cu
> +void apply(std::shared_ptr<const DefaultExecutor> exec,
`DefaultExecutor` makes it easier to copy the code when necessary  :)

2022-02-10 22:49 UTC, upsj approved these changes
LGTM! Can you add your tuning results for the generic reductions here, as well?

2022-02-10 22:49 UTC, upsj commented on hip/matrix/dense_kernels.hip.cpp
> +            GKO_NOT_IMPLEMENTED;
I don't think that's a good alternative, how about deferring to compute_dot here as well?

2022-02-11 07:43 UTC, pratikvn commented
I only ran the tuning results with single vector and with dot product in mind. I did not really verify how that affects the other  kernels using this generic reduction, so I am a bit wary of changing the oversubscription directly in the code as of now. I will try to do a more comprehensive run and update that in another PR.

2022-02-11 13:16 UTC, upsj commented on cuda/matrix/dense_kernels.cu
> +                          x->get_stride, result->get_values());
This is most likely wrong

2022-02-11 13:19 UTC, pratikvn commented on cuda/matrix/dense_kernels.cu
> +                          x->get_stride, result->get_values());
Yikes! Sorry :)

2022-02-11 15:49 UTC, yhmtsai approved these changes
LGTM. could you also add the norm2 test for one vector?
There are 1/20 vectors test for dot and conj_dot but only 20 vectors test for norm2

2022-02-11 15:49 UTC, yhmtsai commented on dpcpp/matrix/dense_kernels.dp.cpp
> +    // TODO Add onemkl for single column ?
could you also copy this TODO to another two?

2022-02-14 07:08 UTC, merged